---
- name: create workdir
  command: mktemp -d /tmp/degoss.XXXXXXXXXX
  register: workdir
  changed_when: degoss_changed_when

# set play facts
- name: establish facts
  set_fact:
    degoss_tmp_root: "{{ workdir.stdout.strip() }}"
    degoss_test_dir: "{{ workdir.stdout.strip() }}/tests"
    degoss_bin_dir: "{{ workdir.stdout.strip() }}/bin"
    degoss_goss_bin: "{{ workdir.stdout.strip() }}/bin/goss"
    goss_file_basename: "{{ goss_file.split('/')[-1] }}"

# create goss directories
- name: create goss directories
  file: path={{ item }} state=directory
  with_items:
    - "{{ degoss_tmp_root }}"
    - "{{ degoss_test_dir }}"
    - "{{ degoss_bin_dir }}"
  changed_when: degoss_changed_when

# deploy test files including the main and additional test files
- name: deploy test files
  copy:
    src: |-
      {%- if item.startswith('/') -%}
        {{ item }}
      {%- else -%}
        {{ playbook_dir | default(".") }}/{{ item }}
      {%- endif -%}
    dest: "{{ degoss_test_dir }}"
    mode: 0644
    directory_mode: 0755
    setype: user_tmp_t
  with_items: "{{ [goss_file] + goss_addtl_files + goss_addtl_dirs }}"
  changed_when: degoss_changed_when

# run the tests
- name: run tests
  degoss:
    bin_dir: "{{ degoss_bin_dir }}"
    log_file: /tmp/degoss.log
    test_dir: "{{ degoss_test_dir }}"
    test_file: "{{ goss_file }}"
  register: goss_output
